# Generated by Django 5.1.6 on 2025-02-16 19:27

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('type', models.CharField(choices=[('SYS', 'System Admin'), ('DG_O', 'Director General Office'), ('SERV', 'Service Deparment'), ('PROG', 'Programme Department'), ('ZONAL', 'Zonal Office'), ('BRANCH', 'Branch'), ('UTILITY', 'Utility Unit')], max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('grade_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('name', models.CharField(max_length=30, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_employee_type', models.CharField(choices=[('SYS', 'System Admin'), ('DG', 'Director General'), ('DIR', 'Director'), ('ZD', 'Zonal Driector'), ('HOD', 'Head of Department'), ('HOU', 'Head of Unit'), ('SC', 'State Coordinator'), ('STAFF', 'Staff')], default='STAFF', max_length=5)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('file_number', models.CharField(max_length=7, verbose_name='File Number')),
                ('ippis_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='IPPIS Number')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Sex')),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True, verbose_name='Marital Status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='Phone Number')),
                ('contact_address', models.CharField(blank=True, max_length=100, verbose_name='Contact Address')),
                ('nin', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='National Identification Number')),
                ('brn', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='Birth Registration Number')),
                ('date_of_appointment', models.DateField(blank=True, null=True, verbose_name='Date on Appointment Letter')),
                ('date_of_documentation', models.DateField(blank=True, null=True, verbose_name='Date of Documentation')),
                ('date_of_assumption', models.DateField(blank=True, null=True, verbose_name='Date of Assumption of Duty')),
                ('date_of_confirmation', models.DateField(blank=True, null=True, verbose_name='Date of Confirmation')),
                ('date_of_retirement', models.DateField(blank=True, null=True, verbose_name='Date of Retirement')),
                ('current_grade_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Current Grade Level')),
                ('current_step', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Current Step')),
                ('current_cadre', models.CharField(blank=True, choices=[('O', 'Officer'), ('E', 'Executive'), ('S', 'Secretariat'), ('C', 'Clerical'), ('D', 'Driver')], max_length=1, null=True, verbose_name='Current Cadre')),
                ('last_promotion_date', models.DateField(blank=True, null=True, verbose_name='Last Promotion Date')),
                ('last_examination_date', models.DateField(blank=True, null=True, verbose_name='Last Examination Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='core.department')),
                ('current_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='core.designation')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('lga_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origins', to='core.lga')),
                ('lga_of_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.lga')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='core.state')),
                ('state_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origins', to='core.state')),
                ('state_of_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.state')),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
            },
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('FSLC', 'First School Leaving Certificate'), ('JSCE', 'Junior School Certificate'), ('SSCE', 'Secondary School Certificate'), ('OND', 'Ordinary National Diploma'), ('HND', 'Higher National Diploma'), ('BAC', 'Bachelors'), ('MAS', 'Masters'), ('DOR', 'Doctorate'), ('PRO', 'Professional')], max_length=4, verbose_name='Qualification Type')),
                ('course_of_study', models.CharField(max_length=50, verbose_name='Course of Study')),
                ('area_of_study', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area of Study')),
                ('institution', models.CharField(max_length=50, verbose_name='Institution')),
                ('year_of_graduation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(core.models.get_current_year)], verbose_name='Year of Graduation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qualifications', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_qualifications', to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='core.employeeprofile')),
            ],
            options={
                'verbose_name': 'Educational Qualification',
                'verbose_name_plural': 'Educational Qualifications',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_formal_eduation', models.CharField(blank=True, choices=[('FSLC', 'First School Leaving Certificate'), ('JSCE', 'Junior School Certificate'), ('SSCE', 'Secondary School Certificate'), ('OND', 'Ordinary National Diploma'), ('HND', 'Higher National Diploma'), ('BAC', 'Bachelors'), ('MAS', 'Masters'), ('DOR', 'Doctorate'), ('PRO', 'Professional')], max_length=4, null=True, verbose_name='Highest Formal Education')),
                ('course_of_study', models.CharField(blank=True, max_length=50, null=True, verbose_name='Course of Study')),
                ('area_of_study', models.CharField(blank=True, help_text='Commerce, Arts, Science, etc.', max_length=50, null=True, verbose_name='Area of Study')),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(core.models.get_current_year)], verbose_name='Year of Graduation')),
                ('account_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Account Number')),
                ('account_type', models.CharField(blank=True, choices=[('SAV', 'Savings'), ('CUR', 'Current')], max_length=3, null=True, verbose_name='Account Type')),
                ('pfa_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='PFA Number')),
                ('leave_status', models.CharField(choices=[('A', 'Active'), ('I', 'On Leave'), ('S', 'Suspended'), ('R', 'Resigned'), ('T', 'Terminated'), ('D', 'Deceased')], default='A', max_length=1, verbose_name='Leave Status')),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Spouse Name')),
                ('spouse_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Spouse Phone Number')),
                ('spouse_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Spouse Email')),
                ('spouse_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spouse Address')),
                ('nok1_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Next of Kin 1 Name')),
                ('nok1_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Next of Kin 1 Phone Number')),
                ('nok1_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Next of Kin 1 Email')),
                ('nok1_relationship', models.CharField(blank=True, choices=[('SPO', 'Spouse'), ('PRT', 'Parent'), ('CHD', 'Child'), ('SIB', 'Sibling'), ('REL', 'Relative'), ('OTH', 'Others')], max_length=3, null=True, verbose_name='Next of Kin 1 Relationship')),
                ('nok1_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin 1 Address')),
                ('nok2_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Next of Kin 2 Name')),
                ('nok2_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Next of Kin 2 Phone Number')),
                ('nok2_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Next of Kin 2 Email')),
                ('nok2_relationship', models.CharField(blank=True, choices=[('SPO', 'Spouse'), ('PRT', 'Parent'), ('CHD', 'Child'), ('SIB', 'Sibling'), ('REL', 'Relative'), ('OTH', 'Others')], max_length=3, null=True, verbose_name='Next of Kin 2 Relationship')),
                ('nok2_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin 2 Address')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.bank')),
                ('employee_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.employeeprofile')),
                ('pfa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.pfa')),
            ],
            options={
                'verbose_name': 'Employee Detail',
                'verbose_name_plural': 'Employee Details',
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='core.state'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.department')),
            ],
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='current_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='core.unit'),
        ),
        migrations.AddField(
            model_name='state',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.zone'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='core.zone'),
        ),
    ]
