# Generated by Django 5.1.6 on 2025-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_present_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Present Appointment'),
        ),
    ]
