# Generated by Django 5.1.6 on 2025-02-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=100)),
                ('check_type', models.CharField(choices=[('AGE_PRIMARY', 'Minimum Age for Primary Education'), ('AGE_SECONDARY', 'Minimum Age for Secondary Education'), ('AGE_TERTIARY', 'Minimum Age for Tertiary Education'), ('EMPLOYMENT_AGE', 'Minimum Age for Employment'), ('MAX_AGE', 'Maximum Age for Employment'), ('EDUCATION_GAP', 'Maximum Gap Between Education Levels'), ('EDUCATION_OVERLAP', 'Education Timeline Overlap')], max_length=20)),
                ('description', models.TextField()),
                ('min_value', models.IntegerField(blank=True, help_text='Minimum value for age checks (in years)', null=True)),
                ('max_value', models.IntegerField(blank=True, help_text='Maximum value for age or gap checks (in years)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Issues Flagged'), ('RESOLVED', 'Issues Resolved'), ('REJECTED', 'Verification Rejected')], default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('flag_category', models.CharField(blank=True, choices=[('AGE', 'Age Discrepancy'), ('EDUCATION', 'Educational Qualification Issue'), ('DOCS', 'Missing Documents'), ('IDENTIFICATION', 'Identification Mismatch'), ('EMPLOYMENT', 'Employment Details Issue'), ('OTHER', 'Other Issues')], max_length=20, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('flagged_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('has_age_flag', models.BooleanField(default=False, help_text='Flagged for age inconsistency')),
                ('has_education_flag', models.BooleanField(default=False, help_text='Flagged for education timeline issues')),
                ('has_employment_flag', models.BooleanField(default=False, help_text='Flagged for employment date issues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.employeeprofile')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_profiles', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_profiles', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Verification Created'), ('VERIFIED', 'Profile Verified'), ('FLAGGED', 'Issues Flagged'), ('RESOLVED', 'Issues Resolved'), ('REJECTED', 'Verification Rejected'), ('UPDATED', 'Profile Updated'), ('AUTO_CHECK', 'Automated Check Performed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.employeeverification')),
            ],
        ),
    ]
