# Generated by Django 5.1.6 on 2025-02-28 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_automatedcheck_employeeverification_verificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_type', models.CharField(choices=[('SYS_ADMIN', 'System Administrator'), ('DG', 'Director General'), ('DIRECTOR', 'Director'), ('ZONAL_DIRECTOR', 'Zonal Director'), ('HOD', 'Head of Department'), ('UNIT_HEAD', 'Unit Head'), ('STATE_COORDINATOR', 'State Coordinator'), ('HR_ADMIN', 'HR Administrator'), ('HR_OFFICER', 'HR Officer'), ('EMPLOYEE', 'Regular Employee')], max_length=20)),
                ('hierarchy_level', models.PositiveIntegerField(default=0)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_departments', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_manage_trainings', models.BooleanField(default=False)),
                ('can_approve_trainings', models.BooleanField(default=False)),
                ('can_manage_leaves', models.BooleanField(default=False)),
                ('can_approve_leaves', models.BooleanField(default=False)),
                ('can_manage_examinations', models.BooleanField(default=False)),
                ('can_manage_promotions', models.BooleanField(default=False)),
                ('can_approve_promotions', models.BooleanField(default=False)),
                ('can_manage_transfers', models.BooleanField(default=False)),
                ('can_approve_transfers', models.BooleanField(default=False)),
                ('can_manage_educational_upgrades', models.BooleanField(default=False)),
                ('can_approve_educational_upgrades', models.BooleanField(default=False)),
                ('can_manage_retirements', models.BooleanField(default=False)),
                ('can_create_tasks', models.BooleanField(default=False)),
                ('can_assign_tasks', models.BooleanField(default=False)),
                ('can_view_all_tasks', models.BooleanField(default=False)),
                ('can_manage_workflows', models.BooleanField(default=False)),
                ('can_manage_files', models.BooleanField(default=False)),
                ('can_view_all_files', models.BooleanField(default=False)),
                ('can_manage_file_permissions', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_create_reports', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_role', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeBasedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('IN', 'In List'), ('NOT_IN', 'Not In List'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('CONTAINS', 'Contains'), ('STARTS_WITH', 'Starts With'), ('ENDS_WITH', 'Ends With')], max_length=15)),
                ('condition_value', models.TextField()),
                ('permission_action', models.CharField(choices=[('VIEW', 'Can View'), ('CHANGE', 'Can Change'), ('ADD', 'Can Add'), ('DELETE', 'Can Delete')], max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_permissions', to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(blank=True, max_length=50, null=True)),
                ('scope_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'scope_type', 'scope_id')},
            },
        ),
    ]
